import { describe, expect, it } from 'vitest';
import { LEVELS, dailyLevel } from '../src/levels';
import { applyHelp, hint, move, startGame, stars, tick, validMove } from '../src/engine/game';
import { RULES } from '../src/engine/config';
import type { Game, Level } from '../src/engine/types';
const fixture = (overrides: Partial<Level> = {}): Level => ({ ...LEVELS[0], board: [[0, 0, 1], [1, 1, 0]].map(row => row.map(item => ({ item, behind: [], unlockAt: 0 }))), seconds: 100, moves: null, objective: { kind: 'clear' }, stars: [500, 700], ...overrides });
function solve(game: Game) { let g = game; let n = 0; while (g.status === 'playing' && n++ < 200) { const m = hint(g); if (!m) throw new Error(`Fase ${g.level.id} sem solução após ${n} trocas`); g = move(g, m); g = tick(g, .5); } return g; }
describe('60 fases', () => {
  it.each(LEVELS.map(l => [l.id, l] as const))('fase %i tem solução sem ajudas dentro dos limites', (_, level) => { const g = solve(startGame(level)); expect(g.status).toBe('won'); expect(g.assisted).toBe(false); expect(g.movesUsed).toBeLessThanOrEqual(level.moves ?? Infinity); expect(g.remaining ?? 1).toBeGreaterThan(0); });
  it('configurações são distintas e determinísticas', () => { expect(new Set(LEVELS.map(l => JSON.stringify(l.board))).size).toBe(60); expect(dailyLevel('2026-10-03')).toEqual(dailyLevel('2026-10-03')); expect(dailyLevel('2026-10-03').seed).not.toBe(dailyLevel('2026-10-04').seed); });
  it.each(LEVELS.map(l => [l.id, l] as const))('fase %i permanece solucionável após reorganizar', (_, level) => { const original = startGame(level); const g = solve(applyHelp(original, 'shuffle')); expect(g.status).toBe('won'); expect(g.assisted).toBe(true); });
  it('100 desafios diários permanecem solucionáveis', () => { for (let i = 0; i < 100; i++) expect(solve(startGame(dailyLevel(`day-${i}`))).status).toBe('won'); });
});
describe('regras do motor', () => {
  const swap = { from: { row: 0, col: 2 }, to: { row: 1, col: 2 } };
  it('troca acessível elimina dois trios e soma combo e bônus', () => { const g = move(startGame(fixture()), swap); expect(g.status).toBe('won'); expect(g.score).toBe(250); expect(g.matches).toBe(2); expect(g.combo).toBe(2); expect(g.resultScore).toBe(1050); expect(g.board.flat().every(s => s.item === null)).toBe(true); });
  it('movimento inválido não modifica nada', () => { const g = startGame(fixture()); const before = JSON.stringify(g); expect(move(g, { from: { row: 99, col: 0 }, to: { row: 0, col: 0 } })).toBe(g); expect(move(g, { from: { row: 0, col: 0 }, to: { row: 0, col: 1 } })).toBe(g); expect(JSON.stringify(g)).toBe(before); });
  it('permite mover para vazio e rejeita fonte vazia', () => { const l = fixture(); l.board[1][2].item = null; const g = startGame(l); expect(validMove(g, { from: { row: 0, col: 1 }, to: { row: 1, col: 2 } })).toBe(true); expect(validMove(g, { from: { row: 1, col: 2 }, to: { row: 0, col: 1 } })).toBe(false); });
  it('desbloqueia buffer depois de trios e revela estoque em cascata', () => { const l = fixture(); l.board.forEach((r, i) => { r.forEach(s => s.behind = [i + 2]); r.push({ item: null, behind: [], unlockAt: 1 }); }); const initial = startGame(l); expect(validMove(initial, { from: { row: 0, col: 0 }, to: { row: 0, col: 3 } })).toBe(false); const g = move(initial, swap); expect(g.matches).toBe(4); expect(g.score).toBe(700); expect(g.board.flat().every(s => !s.behind.length && s.item === null)).toBe(true); });
  it('cronômetro usa tempo decorrido, expira e não altera partida encerrada', () => { const g = tick(startGame(fixture()), 101); expect(g.status).toBe('lost'); expect(g.remaining).toBe(0); expect(g.score).toBe(0); expect(tick(g, 5)).toBe(g); expect(tick(startGame(fixture()), -1).elapsed).toBe(0); });
  it('combo expira após cinco segundos', () => { const g = startGame(fixture()); g.combo = 3; g.lastMatchAt = 0; expect(tick(g, 5).combo).toBe(3); expect(tick(g, 5.01).combo).toBe(0); });
  it('esgota movimentos apenas sem objetivo cumprido', () => { expect(move(startGame(fixture({ moves: 1 })), swap).status).toBe('won'); const g = move(startGame(fixture({ moves: 1 })), { from: { row: 0, col: 0 }, to: { row: 1, col: 0 } }); expect(g.status).toBe('lost'); });
  it('não declara derrota quando há trocas válidas', () => { expect(tick(startGame(fixture()), 1).status).toBe('playing'); });
  it('objetivos especiais vencem sem limpar todo o estoque', () => { const l = fixture({ objective: { kind: 'order', product: 0, count: 3 } }); l.board.push([2, 2, 3].map(item => ({ item, behind: [], unlockAt: 0 }))); const g = move(startGame(l), swap); expect(g.status).toBe('won'); expect(g.board[2][0].item).toBe(2); expect(move(startGame(fixture({ objective: { kind: 'score', target: 200 } })), swap).status).toBe('won'); });
  it('desfazer restaura estado e pontos sem devolver tempo', () => { const g = startGame(fixture()); const after = tick(move(g, { from: { row: 0, col: 0 }, to: { row: 1, col: 0 } }), 4); const undone = applyHelp(after, 'undo'); expect(undone.board).toEqual(g.board); expect(undone.score).toBe(0); expect(undone.movesUsed).toBe(0); expect(undone.remaining).toBe(96); expect(undone.assisted).toBe(true); });
  it('dica é válida, não pontua; tempo extra soma 30', () => { const g = startGame(fixture()); const h = applyHelp(g, 'hint'); expect(validMove(h, h.hints!)).toBe(true); expect(h.score).toBe(0); expect(applyHelp(g, 'time').remaining).toBe(130); });
  it('reorganizar não pontua nem mantém combo', () => { const g = startGame(fixture()); g.combo = 2; const s = applyHelp(g, 'shuffle'); expect(s.score).toBe(0); expect(s.combo).toBe(0); });
  it('metas de estrelas são inclusivas e derrota nunca dá estrela', () => { expect(stars(499, [500, 700])).toBe(1); expect(stars(500, [500, 700])).toBe(2); expect(stars(700, [500, 700])).toBe(3); expect(stars(10000, [500, 700], false)).toBe(0); });
  it('configuração inicial não é modificada pelo motor', () => { const l = fixture(), before = JSON.stringify(l); move(startGame(l), swap); expect(JSON.stringify(l)).toBe(before); });
  it('bônus por movimentos restantes é configurável', () => { const g = move(startGame(fixture({ moves: 5, seconds: null })), swap); expect(g.resultScore).toBe(250 + RULES.completion + 4 * RULES.move); });
});
