import { describe, expect, it } from 'vitest';
import { createLocalServices } from '../src/services/local';
import { defaultProgress, localDay } from '../src/services/progress';
import type { Persistence } from '../integration/contracts';
import type { Result } from '../src/engine/types';
import { LEVELS, dailyLevel } from '../src/levels';
import { applyHelp, hint, move, startGame, stars, tick } from '../src/engine/game';
import type { Game, Level } from '../src/engine/types';
function storage(): Persistence { const values = new Map<string, string>(); return { read: k => values.get(k) ?? null, write: (k, v) => { values.set(k, v); } }; }
function toResult(g: Game, r: Partial<Result> = {}): Result { return { runId: 'first', levelId: g.level.id, seed: g.level.seed, configVersion: g.level.configVersion, score: g.resultScore ?? g.score, stars: stars(g.resultScore ?? g.score, g.level.stars, g.status === 'won'), won: g.status === 'won', assisted: g.assisted, elapsed: g.elapsed, moves: g.movesUsed, daily: false, dailyDay: g.level.dailyDay, events: g.events, ...r }; }
function solve(l: Level, slow = false) { let g = startGame(l); if (slow) g = tick(g, 118); while (g.status === 'playing') { if (slow) g = tick(g, 6); g = move(g, hint(g)!); } return g; }
const result = (r: Partial<Result> = {}) => toResult(solve(LEVELS[0]), r);
const lowResult = (runId = 'low') => toResult(solve(LEVELS[0], true), { runId });
const dailyResult = (runId = 'daily') => toResult(solve(dailyLevel(localDay())), { runId, daily: true });
describe('persistência e economia simulada', () => {
  it('recompensas são únicas por fase, estrela e dia; submissão é idempotente', async () => { const s = createLocalServices(storage()); const first = await s.submitResult(result()); expect(first.awarded).toBe(13); expect((await s.submitResult(result())).awarded).toBe(13); expect(await s.getBalance()).toBe(63); expect((await s.submitResult(result({ runId: 'second' }))).awarded).toBe(0); expect(await s.getBalance()).toBe(63); });
  it('repetição inferior preserva recorde, estrelas e desbloqueio', async () => { const s = createLocalServices(storage()); await s.submitResult(result()); const low = await s.submitResult(lowResult()); expect(low.progress.records[1]).toEqual({ stars: 3, score: result().score, completed: true }); expect(low.progress.unlocked).toBe(2); });
  it('primeira terceira estrela pode vir numa repetição', async () => { const s = createLocalServices(storage()); expect(lowResult().stars).toBe(1); expect((await s.submitResult(lowResult())).awarded).toBe(10); expect((await s.submitResult(result({ runId: 'three' }))).awarded).toBe(3); });
  it('derrota não desconta moedas nem desbloqueia', async () => { const s = createLocalServices(storage()); const r = await s.submitResult(toResult(tick(startGame(LEVELS[0]), 136))); expect(r.balance).toBe(50); expect(r.awarded).toBe(0); expect(r.progress.unlocked).toBe(1); });
  it('compra idempotente e saldo insuficiente não fica negativo', async () => { const s = createLocalServices(storage()); const buy = { requestId: 'a', runId: 'g', help: 'shuffle' as const, levelId: 1 }; await s.purchaseHelp(buy); await s.purchaseHelp(buy); expect(await s.getBalance()).toBe(30); await s.purchaseHelp({ ...buy, requestId: 'b' }); expect((await s.purchaseHelp({ ...buy, requestId: 'c' })).approved).toBe(false); expect(await s.getBalance()).toBe(10); });
  it('novas instâncias recuperam progresso, preferências, saldo e recibos', async () => { const p = storage(), s = createLocalServices(p); await s.submitResult(result()); const prog = await s.loadProgress(); await s.saveProgress({ ...prog, tutorialDone: true, preferences: { sound: true, reducedMotion: true } }); const recovered = createLocalServices(p); expect(await recovered.loadProgress()).toMatchObject({ unlocked: 2, tutorialDone: true, preferences: { sound: true, reducedMotion: true } }); expect(await recovered.getBalance()).toBe(63); expect((await recovered.submitResult(result())).balance).toBe(63); });
  it('desafio diário não desbloqueia campanha e recompensa uma vez ao dia', async () => { const s = createLocalServices(storage()); expect((await s.submitResult(dailyResult())).awarded).toBe(15); expect((await s.submitResult(dailyResult('daily-2'))).awarded).toBe(0); expect((await s.loadProgress()).unlocked).toBe(1); });
  it('usa dia civil de São Paulo para recompensa diária', () => { expect(localDay(new Date('2026-10-04T01:00:00Z'))).toBe('2026-10-03'); });
  it('mudança de dia libera primeira vitória diária sem repetir recompensa da fase', async () => { let d = '2026-10-03'; const s = createLocalServices(storage(), 'u', () => d); await s.submitResult(result()); d = '2026-10-04'; expect((await s.submitResult(result({ runId: 'next-day' }))).awarded).toBe(5); });
  it('isola identidades e filtra ranking por configuração', async () => { const p = storage(), a = createLocalServices(p, 'a'), b = createLocalServices(p, 'b'); await a.submitResult(result()); expect(await b.getBalance()).toBe(50); expect(await a.getRanking({ mode: 'couple', levelId: 1, seed: 9 })).toEqual([]); const ranking = await a.getRanking({ mode: 'group', levelId: 1, seed: 7919, configVersion: 2 }); expect(ranking[0].assisted).toBe(false); });
  it('rejeita resultados de fases bloqueadas e valores inválidos', async () => { const s = createLocalServices(storage()); await expect(s.submitResult(result({ levelId: 60 }))).rejects.toThrow(); await expect(s.submitResult(result({ score: NaN }))).rejects.toThrow(); await expect(s.submitResult(result({ stars: 4 }))).rejects.toThrow(); });
  it('salvar preferências não apaga nem forja progresso', async () => { const s = createLocalServices(storage()); await s.submitResult(result()); await s.saveProgress({ ...defaultProgress(), unlocked: 60 }); expect((await s.loadProgress()).records[1].score).toBe(result().score); expect((await s.loadProgress()).unlocked).toBe(2); });
  it('rejeita pontuação plausível sem replay válido e diário com semente errada', async () => { const s = createLocalServices(storage()); await expect(s.submitResult(result({ score: result().score + 50 }))).rejects.toThrow(); await expect(s.submitResult({ ...dailyResult('fake-seed'), seed: 123 })).rejects.toThrow(); expect(await s.getBalance()).toBe(50); });
  it('chave de compra não pode ser reaproveitada para outro recurso', async () => { const s = createLocalServices(storage()); const purchase = { requestId: 'one', runId: 'game', levelId: 1, help: 'hint' as const }; await s.purchaseHelp(purchase); await expect(s.purchaseHelp({ ...purchase, help: 'time' })).rejects.toThrow(); expect(await s.getBalance()).toBe(40); });
  it('desafio iniciado antes da meia-noite mantém o dia de sua recompensa', async () => { let d = '2026-10-03'; const s = createLocalServices(storage(), 'u', () => d); const r = toResult(solve(dailyLevel(d)), { daily: true }); d = '2026-10-04'; expect((await s.submitResult(r)).awarded).toBe(15); expect((await s.submitResult({ ...r, runId: 'repeat-yesterday' })).awarded).toBe(0); });
  it('resultado com ajuda exige recibo correspondente', async () => { const s = createLocalServices(storage()); let g = applyHelp(startGame(LEVELS[0]), 'time'); while (g.status === 'playing') g = move(g, hint(g)!); const r = toResult(g, { runId: 'aid' }); await expect(s.submitResult(r)).rejects.toThrow('Ajuda sem compra'); await s.purchaseHelp({ requestId: 'paid', runId: 'aid', levelId: 1, help: 'time' }); expect((await s.submitResult(r)).balance).toBe(48); });
});

