import { build } from 'esbuild';
import fs from 'node:fs';
const result = await build({ stdin: { contents: "export { LEVELS, PACKS } from './src/levels/index.ts'; export { PRODUCTS } from './src/engine/config.ts';", resolveDir: process.cwd(), loader: 'ts' }, bundle: true, write: false, format: 'esm', platform: 'node' });
const { LEVELS, PACKS, PRODUCTS } = await import('data:text/javascript;base64,' + Buffer.from(result.outputFiles[0].text).toString('base64'));
const objective = l => l.objective.kind === 'clear' ? 'Eliminar todo o estoque' : l.objective.kind === 'score' ? `${l.objective.target} pontos de combinações` : `${l.objective.count} × ${PRODUCTS[l.objective.product].name}`;
let doc = '# Catálogo das 60 fases — configuração 2\n\nGerado pela configuração executada pelo jogo (`npm run docs:levels`). Sementes e tabuleiros são estáveis entre participantes da mesma versão. A primeira dezena mantém o tabuleiro anterior; fases 11–60 ampliam o estoque. Prateleiras nesta tabela são compartimentos independentes: duas por fileira no mobile, até três no desktop largo. Configuração 1 permanece em src/levels/legacy.ts para validar partidas anteriores.\n\n';
doc += '| Fase | Conjunto | Prateleiras × espaços | Frente / atrás / vazios | Tipos | Camadas atrás | Objetivo | Segundos | Movimentos | 2★ / 3★ |\n|---|---|---|---|---|---|---|---|---|---|\n';
for (const l of LEVELS) doc += `| ${l.id} | ${l.pack + 1} | ${l.board.length} × ${l.board[0].length} | ${l.board.flat().filter(s => s.item !== null).length} / ${l.board.flat().reduce((sum, s) => sum + s.behind.length, 0)} / ${l.board.flat().filter(s => s.item === null).length} | ${l.types} | ${Math.max(...l.board.flat().map(s => s.behind.length))} | ${objective(l)} | ${l.seconds ?? 'Livre'} | ${l.moves ?? 'Livre'} | ${l.stars.join(' / ')} |\n`;
doc += '\n## Progressão e solução\n\nConjuntos 1–2: trios acessíveis, maior variedade e mais prateleiras. Conjunto 3: camadas de estoque e espaços extras bloqueados. Conjunto 4: limites de trocas. Conjuntos 5–6: pedidos e pontuação combinados com obstáculos. O tempo diminui gradualmente dentro de cada conjunto. As camadas posteriores são lotes de três iguais: só se revelam quando a frente inteira da prateleira, incluindo o buffer, estiver vazia. O cadeado bloqueia apenas buffers vazios; nenhum item obrigatório exige pagar por ajuda.\n\nO algoritmo de dica constrói uma solução: escolhe um tipo presente numa prateleira e traz exemplares de outras, formando três. Os totais acessíveis são múltiplos de três; as camadas escondidas revelam novos lotes completos. A suíte executa as 60 soluções dentro dos limites, antes e depois de reorganizar. Isso prova existência de solução, não garante que qualquer sequência de trocas respeite o limite de tempo ou movimentos.\n\n## Disposições iniciais\n\nIDs de produto: ' + PRODUCTS.map((p, i) => `${i}=${p.name}`).join(', ') + '.\n\nCada linha é uma prateleira. `·` é espaço vazio; `▣N` é um buffer que abre após N trios. A lista “atrás” é revelada por camada, uma coluna por espaço.\n';
for (const l of LEVELS) {
  doc += `\n### Fase ${l.id} — ${PACKS[l.pack]}\n\nDificuldade: ${l.difficulty}. Semente: ${l.seed}. Mecânicas: ${l.mechanics.join(', ')}. Objetivo: ${objective(l)}.\n\n\`\`\`text\n`;
  for (const row of l.board) doc += row.map(s => s.unlockAt ? `▣${s.unlockAt}` : s.item ?? '·').join(' | ') + '    atrás: ' + row.map(s => s.behind.length ? `[${s.behind.join(',')}]` : '[]').join(' ') + '\n';
  doc += '\`\`\`\n';
}
fs.writeFileSync('LEVELS.md', doc);
fs.writeFileSync('levels.snapshot.json', JSON.stringify(LEVELS, null, 2) + '\n');
console.log('LEVELS.md e levels.snapshot.json atualizados: 60 fases.');
